"""Added driver tables

Revision ID: fd95d6628f3c
Revises: 
Create Date: 2021-04-25 17:56:42.537674

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.


revision = 'fd95d6628f3c'
down_revision = None
branch_labels = None
depends_on = None






def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_types',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon_file_path', sa.String(), nullable=True),
    sa.Column('logo_file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drivers',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('jdbc_class_name', sa.String(), nullable=True),
    sa.Column('url_template', sa.String(), nullable=True),
    sa.Column('default_port', sa.Integer(), nullable=True),
    sa.Column('is_predefined', sa.Boolean(), nullable=True),
    sa.Column('driver_type_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['driver_type_id'], ['driver_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('driver_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('driver_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', 'driver_id')
    )
    op.create_table('expected_driver_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('file_regex', sa.String(), nullable=True),
    sa.Column('driver_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_regex', 'driver_id')
    )
    # ### end Alembic commands ###

    # Insert data



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expected_driver_files')
    op.drop_table('driver_files')
    op.drop_table('drivers')
    op.drop_table('driver_types')
    # ### end Alembic commands ###
