# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/driver_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DriverSelector(object):
    def setupUi(self, DriverSelector):
        DriverSelector.setObjectName("DriverSelector")
        DriverSelector.resize(606, 382)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources_data/app_icon/database_drivers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DriverSelector.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DriverSelector)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listView = QtWidgets.QListView(DriverSelector)
        self.listView.setObjectName("listView")
        self.verticalLayout_2.addWidget(self.listView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(DriverSelector)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.nextButton = QtWidgets.QPushButton(DriverSelector)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(DriverSelector)
        QtCore.QMetaObject.connectSlotsByName(DriverSelector)

    def retranslateUi(self, DriverSelector):
        _translate = QtCore.QCoreApplication.translate
        DriverSelector.setWindowTitle(_translate("DriverSelector", "Select Driver"))
        self.cancelButton.setText(_translate("DriverSelector", "Cancel"))
        self.nextButton.setText(_translate("DriverSelector", "Next"))
from . import resources_rc
