# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/driver_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DriverManager(object):
    def setupUi(self, DriverManager):
        DriverManager.setObjectName("DriverManager")
        DriverManager.resize(739, 635)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DriverManager)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetHorizontalLayout = QtWidgets.QHBoxLayout()
        self.widgetHorizontalLayout.setObjectName("widgetHorizontalLayout")
        self.listView = QtWidgets.QListView(DriverManager)
        self.listView.setObjectName("listView")
        self.widgetHorizontalLayout.addWidget(self.listView)
        self.buttonsVerticalLayout = QtWidgets.QVBoxLayout()
        self.buttonsVerticalLayout.setObjectName("buttonsVerticalLayout")
        self.newButton = QtWidgets.QPushButton(DriverManager)
        self.newButton.setObjectName("newButton")
        self.buttonsVerticalLayout.addWidget(self.newButton)
        self.editButton = QtWidgets.QPushButton(DriverManager)
        self.editButton.setObjectName("editButton")
        self.buttonsVerticalLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(DriverManager)
        self.deleteButton.setObjectName("deleteButton")
        self.buttonsVerticalLayout.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.buttonsVerticalLayout.addItem(spacerItem)
        self.widgetHorizontalLayout.addLayout(self.buttonsVerticalLayout)
        self.verticalLayout_3.addLayout(self.widgetHorizontalLayout)
        self.bottomButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonsHorizontalLayout.setObjectName("bottomButtonsHorizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtonsHorizontalLayout.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(DriverManager)
        self.okButton.setObjectName("okButton")
        self.bottomButtonsHorizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(DriverManager)
        self.cancelButton.setObjectName("cancelButton")
        self.bottomButtonsHorizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout_3.addLayout(self.bottomButtonsHorizontalLayout)

        self.retranslateUi(DriverManager)
        QtCore.QMetaObject.connectSlotsByName(DriverManager)

    def retranslateUi(self, DriverManager):
        _translate = QtCore.QCoreApplication.translate
        DriverManager.setWindowTitle(_translate("DriverManager", "Driver Manager"))
        self.newButton.setText(_translate("DriverManager", "New"))
        self.editButton.setText(_translate("DriverManager", "Edit"))
        self.deleteButton.setText(_translate("DriverManager", "Delete"))
        self.okButton.setText(_translate("DriverManager", "Ok"))
        self.cancelButton.setText(_translate("DriverManager", "Cancel"))
from . import resources_rc
