# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design/generic_crud_listview_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenericLisviewItemManager(object):
    def setupUi(self, GenericLisviewItemManager):
        GenericLisviewItemManager.setObjectName("GenericLisviewItemManager")
        GenericLisviewItemManager.resize(739, 635)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources_data/app_icon/database_drivers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GenericLisviewItemManager.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(GenericLisviewItemManager)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetHorizontalLayout = QtWidgets.QHBoxLayout()
        self.widgetHorizontalLayout.setObjectName("widgetHorizontalLayout")
        self.listView = QtWidgets.QListView(GenericLisviewItemManager)
        self.listView.setObjectName("listView")
        self.widgetHorizontalLayout.addWidget(self.listView)
        self.buttonsVerticalLayout = QtWidgets.QVBoxLayout()
        self.buttonsVerticalLayout.setObjectName("buttonsVerticalLayout")
        self.newButton = QtWidgets.QPushButton(GenericLisviewItemManager)
        self.newButton.setObjectName("newButton")
        self.buttonsVerticalLayout.addWidget(self.newButton)
        self.editButton = QtWidgets.QPushButton(GenericLisviewItemManager)
        self.editButton.setObjectName("editButton")
        self.buttonsVerticalLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(GenericLisviewItemManager)
        self.deleteButton.setObjectName("deleteButton")
        self.buttonsVerticalLayout.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.buttonsVerticalLayout.addItem(spacerItem)
        self.widgetHorizontalLayout.addLayout(self.buttonsVerticalLayout)
        self.verticalLayout_3.addLayout(self.widgetHorizontalLayout)
        self.bottomButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.bottomButtonsHorizontalLayout.setObjectName("bottomButtonsHorizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomButtonsHorizontalLayout.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(GenericLisviewItemManager)
        self.okButton.setObjectName("okButton")
        self.bottomButtonsHorizontalLayout.addWidget(self.okButton)
        self.verticalLayout_3.addLayout(self.bottomButtonsHorizontalLayout)

        self.retranslateUi(GenericLisviewItemManager)
        QtCore.QMetaObject.connectSlotsByName(GenericLisviewItemManager)

    def retranslateUi(self, GenericLisviewItemManager):
        _translate = QtCore.QCoreApplication.translate
        GenericLisviewItemManager.setWindowTitle(_translate("GenericLisviewItemManager", "Driver Manager"))
        self.newButton.setText(_translate("GenericLisviewItemManager", "New"))
        self.editButton.setText(_translate("GenericLisviewItemManager", "Edit"))
        self.deleteButton.setText(_translate("GenericLisviewItemManager", "Delete"))
        self.okButton.setText(_translate("GenericLisviewItemManager", "Ok"))
from . import resources_rc
